<?php

namespace Database\Seeders;

use App\Models\LaporanHpio;
use Illuminate\Database\Seeder;

class LaporanHpioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'idNumber' => 'HPIO-INC-140526-209',
                'timestamp' => '2026-05-14 07:59:19.000',
                'nomor_tiket' => 'HPIO-INC-140526-209',
                'tanggal_lapor' => '2026-05-14',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'TEGALLUAR',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 402',
                'deskripsi_masalah' => 'Selamat siang mas, mohon tolong bantuannya di tvm 402 tegalluar, status nya gagal cetak tiket. 🙏',
                'skala_prioritas' => 'P2',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-14 14:58:58.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-180526-013',
                'timestamp' => '2026-05-18 08:36:14.000',
                'nomor_tiket' => 'HPIO-INC-180526-013',
                'tanggal_lapor' => '2026-05-18',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'HALIM',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 TVM 122 halim dicuri jalu',
                'skala_prioritas' => 'P1',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-18 08:35:54.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-190526-004',
                'timestamp' => '2026-05-19 12:48:16.000',
                'nomor_tiket' => 'HPIO-INC-190526-004',
                'tanggal_lapor' => '2026-05-19',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'HALIM',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 TVM 111 halim mengalami penangguhan tolong di FU',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-19 19:47:57.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-200526-002',
                'timestamp' => '2026-05-20 22:09:20.000',
                'nomor_tiket' => 'HPIO-INC-200526-002',
                'tanggal_lapor' => '2026-05-20',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'ahmad ali yasin',
                'stasiun_lokasi' => 'PADALARANG',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 Bapak/Ibu mohon dibantu untuk TVM di Lantai 1 St Padalarang mengalami gangguan dalam proses percetakan tiket, mohon untuk dibantu 🙏',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => 'ahmad ali yasin',
                'waktu_melapor' => '2026-05-20 22:08:29.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '2026-05-20 15:22:33.000',
                'respon_time' => '2026-05-20 22:09:32',
                'solving_time' => '15:22:33 menit',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-200526-006',
                'timestamp' => '2026-05-20 23:14:15.000',
                'nomor_tiket' => 'HPIO-INC-200526-006',
                'tanggal_lapor' => '2026-05-20',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'ahmad ali yasin',
                'stasiun_lokasi' => 'PADALARANG',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 Bapak/Ibu mohon dibantu untuk TVM 303\ di Lantai 1 St Padalarang mengalami gangguan dalam proses percetakan tiket, mohon untuk dibantu 🙏',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => 'ahmad ali yasin',
                'waktu_melapor' => '2026-05-20 23:12:00.000',
                'waktu_respon_teknisi' => '2026-05-20 02:31:00.000',
                'waktu_selesai' => '2026-05-20 23:19:15.000',
                'respon_time' => '2026-05-20 23:14:31',
                'solving_time' => '07:15',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-190526-008',
                'timestamp' => '2026-05-19 22:36:52.000',
                'nomor_tiket' => 'HPIO-INC-190526-008',
                'tanggal_lapor' => '2026-05-19',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'ahmad ali yasin',
                'stasiun_lokasi' => 'HALIM',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 TVM 103 halim mengalami penangguhan tolong di FU',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => 'ahmad ali yasin',
                'waktu_melapor' => '2026-05-19 22:36:35.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '2026-05-19 15:37:18.000',
                'respon_time' => '2026-05-19 15:37:18',
                'solving_time' => '00:00 menit',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-200526-003',
                'timestamp' => '2026-05-20 22:41:33.000',
                'nomor_tiket' => 'HPIO-INC-200526-003',
                'tanggal_lapor' => '2026-05-20',
                'nama_pelapor' => 'ahmad ali yasin',
                'nama_penerima_laporan' => 'ahmad ali yasin',
                'stasiun_lokasi' => 'PADALARANG',
                'kategori_aset' => 'TVM',
                'equipment' => 'TVM',
                'deskripsi_masalah' => '@13035980734713 Bapak/Ibu mohon dibantu untuk TVM 305 di Lantai 1 St Padalarang mengalami gangguan dalam proses percetakan tiket, mohon untuk dibantu 🙏',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => 'ahmad ali yasin',
                'waktu_melapor' => '2026-05-20 22:40:48.000',
                'waktu_respon_teknisi' => '2026-05-20 00:59:00.000',
                'waktu_selesai' => '2026-05-20 23:02:17.000',
                'respon_time' => '2026-05-20 22:41:47',
                'solving_time' => '21:29',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-160526-948',
                'timestamp' => '2026-05-16 08:19:05.000',
                'nomor_tiket' => 'HPIO-INC-160526-948',
                'tanggal_lapor' => '2026-05-16',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'TEGALLUAR',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 404',
                'deskripsi_masalah' => '@13035980734713 tvm 404 stasiun tegalluar tvm hilang dicuri maling',
                'skala_prioritas' => 'P1',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-16 15:18:49.000',
                'waktu_respon_teknisi' => '2026-05-16 08:19:23.000',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-140526-166',
                'timestamp' => '2026-05-14 08:45:07.000',
                'nomor_tiket' => 'HPIO-INC-140526-166',
                'tanggal_lapor' => '2026-05-14',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'TEGALLUAR',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 404',
                'deskripsi_masalah' => 'Permisi tvm 404 stasiun tegalluar penangguhan',
                'skala_prioritas' => 'P2',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-14 15:44:05.000',
                'waktu_respon_teknisi' => '2026-05-14 08:45:50.000',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-140526-037',
                'timestamp' => '2026-05-14 08:15:28.000',
                'nomor_tiket' => 'HPIO-INC-140526-037',
                'tanggal_lapor' => '2026-05-14',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'TEGALLUAR',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 402',
                'deskripsi_masalah' => 'status gagal cetak tiket, segera di tl',
                'skala_prioritas' => 'P2',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-14 08:15:03.000',
                'waktu_respon_teknisi' => '2026-05-14 08:38:18.000',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-160526-606',
                'timestamp' => '2026-05-16 08:28:14.000',
                'nomor_tiket' => 'HPIO-INC-160526-606',
                'tanggal_lapor' => '2026-05-16',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'KARAWANG',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 201',
                'deskripsi_masalah' => '@13035980734713 tvm 201 stasiun Karawang rusak upsnya',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-16 08:27:59.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ],
            [
                'idNumber' => 'HPIO-INC-160526-556',
                'timestamp' => '2026-05-16 08:40:10.000',
                'nomor_tiket' => 'HPIO-INC-160526-556',
                'tanggal_lapor' => '2026-05-16',
                'nama_pelapor' => 'Dastin',
                'nama_penerima_laporan' => 'HPIO On Duty',
                'stasiun_lokasi' => 'PADALARANG',
                'kategori_aset' => 'TVM',
                'equipment' => 'tvm 303',
                'deskripsi_masalah' => '@13035980734713 izin it tvm 303 stasiun Padalarang mengalami gangguan',
                'skala_prioritas' => 'P3',
                'status_laporan' => 'CLOSE',
                'nama_teknisi' => null,
                'waktu_melapor' => '2026-05-16 08:40:00.000',
                'waktu_respon_teknisi' => '',
                'waktu_selesai' => '',
                'respon_time' => '0',
                'solving_time' => '0',
                'wr_doc_nomor' => null,
                'status_eskalasi' => 'NO',
                'bulan' => 'Mei 2026',
            ]
        ];

        foreach ($data as $row) {
            LaporanHpio::updateOrCreate(['idNumber' => $row['idNumber']], $row);
        }
    }
}
